### ISSUE TITLE
My Pen URL Isn't Work 

### ISSUE THREAD

**Issue by khaalf** [ak4t0sh/moodle-filter_codepen#7]
Hi, my CodePen URL still in the form of link while the example URL worked perfectly. 
My Pen link is https://codepen.io/khaalf-the-lessful/pen/VwPOdEa
and I use Moodle version 3.9.6+ and plugin version 3.4
Can you tell me where I went wrong? Thanks a lot.

![image](https://user-images.githubusercontent.com/62366055/116815419-b1643080-ab87-11eb-86de-e0282051d309.png)

**Comment by ak4t0sh** [comment]
Hi, Thanks for reporting this issue.
It seems to be a duplicate for #6.
I'll try to fix it soon  but if in the mean time you are able to provide a fix do not hesitate to fill a PR.

**Comment by ak4t0sh** [comment]
Fixed in 3.4.1
