### ISSUE TITLE
Breaks "Add Activity" in Moodle 4.1using PHP 8

### ISSUE THREAD

**Issue by hr-curtissimo** [ak4t0sh/moodle-filter_codepen#8]
When `CodePen` is enabled, the "Add Activity" popup is broken. It works just fine in the filter rendering on a normal page from a student's point of view.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/34490321/221021987-eb56e581-b0d6-41c7-aae9-b50725c56978.png">

**Comment by ak4t0sh** [comment]
Thanks for the report.
This issue is not related to moodle version but to the PHP version.
Indeed (using Moodle 4.1) :
* PHP 8.x => KO
* PHP 7.4 => OK

I'll try to work on it soon but in the mean time if you have developed a patch do not hesitate to do a PR and I'll review it :)

**Comment by ak4t0sh** [comment]
Thanks for your patience.
Fix integrated and available in release 3.4.2
